### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by daedeloth** [steffest/Stieviewer#1]
TypeError: Cannot call method 'replace' of undefined
    at Object.exports.replaceAll (/home/daedeloth/Stievie/node_modules/Stieviewer/lib/stringutil.js:3:16)
    at Request._callback (/home/daedeloth/Stievie/node_modules/Stieviewer/lib/stievie.js:283:27)
    at self.callback (/home/daedeloth/Stievie/node_modules/Stieviewer/node_modules/request/request.js:373:22)
    at Request.emit (events.js:95:17)
    at Request.onRequestError (/home/daedeloth/Stievie/node_modules/Stieviewer/node_modules/request/request.js:971:8)
    at ClientRequest.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1551:9)
    at CleartextStream.emit (events.js:95:17)
    at Socket.onerror (tls.js:1455:17)
    at Socket.emit (events.js:117:20)

**Comment by steffest** [comment]
The error is handled now in master , but still this is not normal behaviour.
Does it happen with every program you start or just when you enter a "greyed out" program?
Or maybe caused by a temporary network drop?

**Comment by daedeloth** [comment]
I suspect there was a temporary network drop.

2015-02-10 8:58 GMT+01:00 Steffest <notifications@github.com>:
