### ISSUE TITLE
Nog eentje ;-)

### ISSUE THREAD

**Issue by daedeloth** [steffest/Stieviewer#2]
loading https://playlistsvr-stievie.triple-it.nl:443/Default.m3u8?streamname=vier&streamid=67&currenttime=1423764866&urlvalidity=2400&streamduration=14400&userid=0&key=89733783F9434136A776887B479D58BDC4D4A7BE&session=e63f73297655425cac214785bae0cca4&index=2&time=1423767354105
proxying AES Key
refreshing Channels
10 channels found
refreshing EPG
10 epg channels found

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.header (/home/daedeloth/Stievie/node_modules/Stieviewer/node_modules/express/lib/response.js:666:10)
    at ServerResponse.send (/home/daedeloth/Stievie/node_modules/Stieviewer/node_modules/express/lib/response.js:146:12)
    at ServerResponse.json (/home/daedeloth/Stievie/node_modules/Stieviewer/node_modules/express/lib/response.js:235:15)
    at Request._callback (/home/daedeloth/Stievie/node_modules/Stieviewer/lib/stievie.js:259:33)
    at Request.self.callback (/home/daedeloth/Stievie/node_modules/Stieviewer/node_modules/request/request.js:373:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/daedeloth/Stievie/node_modules/Stieviewer/node_modules/request/request.js:1318:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/daedeloth/Stievie/node_modules/Stieviewer/node_modules/request/request.js:1266:12)

**Comment by steffest** [comment]
True!

Fixed in latest master (V 0.0.2)
